FROM python:3.8-alpine
ENV PYTHONUNBUFFERED 1

# Allows docker to cache installed dependencies between builds
COPY Pipfile* ./
RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile

# Adds our application code to the image
COPY . /code/
WORKDIR /code

# Expose Django's port
EXPOSE $PORT
