# Generated by Django 2.2 on 2019-11-24 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='app name')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='api key')),
            ],
        ),
    ]
